VideogamesCodex/VideogamesCodex/VideogamesCodex/urls.py
"""
Definition of urls for VideogamesCodex.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views

import app.forms
import app.views

# Uncomment the next lines to enable the admin:
# from django.conf.urls import include
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^show/(?P<id>[0-9]+)$', app.views.show, name='show'),
    url(r'^create', app.views.create, name='create'),
    url(r'^edit/(?P<id>[0-9]+)$', app.views.edit, name='edit'),
    url(r'^remove/(?P<id>[0-9]+)$', app.views.remove, name='remove'),
    url(r'^ranking', app.views.ranking, name='ranking'),
    url(r'', app.views.not_found,name=""),
    #url(r'^login/$',
    #    django.contrib.auth.views.login,
    #    {
    #        'template_name': 'app/login.html',
    #        'authentication_form': app.forms.BootstrapAuthenticationForm,
    #        'extra_context':
    #        {
    #            'title': 'Log in',
    #            'year': datetime.now().year,
    #        }
    #    },
    #    name='login'),
    #url(r'^logout$',
    #    django.contrib.auth.views.logout,
    #    {
    #        'next_page': '/',
    #    },
    #    name='logout'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
]

VideogamesCodex/VideogamesCodex/app/models.py
"""
Definition of models.
"""

from django.db import models

class Game(models.Model):
    name = models.CharField(max_length=50)
    publisher = models.CharField(max_length=20)
    year = models.IntegerField()
    GENRES = ((0,"Action"),(1,"Adventure"),(2,"Strategy"),(3,"RPG"),(4,"Sport"))
    genre = models.IntegerField(choices=GENRES)
    PLATFORMS = ((0,"PC"),(1,"PS4"),(2,"XBOXONE"))
    platform = models.IntegerField(choices=PLATFORMS)
    score = models.IntegerField()
    online=models.BooleanField()
    pegi=models.IntegerField()

    #devolver todas las series
    def getGames():
        games = Game.objects.all()
        return games

    def getGame(clave):
        try:
            game = Game.objects.get(pk=clave)
        except Game.DoesNotExist:
            game = None

        return game

    def getGamesByFilter():
        games = Game.objects.values_list("id","name","score").order_by("score").reverse()
        return games
    def getGameSearch(data):
        
        try:
            games = Game.objects.filter(name__icontains=data)|Game.objects.filter(publisher__icontains=data)
        except Game.DoesNotExist:
            games = None
        return games

    

VideogamesCodex/VideogamesCodex/app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from app.models import Game

#class BootstrapAuthenticationForm(AuthenticationForm):
#    """Authentication form which uses boostrap CSS."""
#    username = forms.CharField(max_length=254,
#                               widget=forms.TextInput({
#                                   'class': 'form-control',
#                                   'placeholder': 'User name'}))
#    password = forms.CharField(label=_("Password"),
#                               widget=forms.PasswordInput({
#                                   'class': 'form-control',
#                                   'placeholder':'Password'}))

class FormGame(forms.ModelForm):
    name=forms.CharField(max_length=50,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'name of game'}),required=True)
    publisher=forms.CharField(max_length=20,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Publisher Game'}),required=True)
    year=forms.IntegerField(
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Year game'}),required=True)
    genre=forms.ChoiceField(choices=Game.GENRES,
                               widget=forms.Select({
                                   'class': 'form-control'}),required=True)
    platform=forms.ChoiceField(choices=Game.PLATFORMS,
                               widget=forms.Select({
                                   'class': 'form-control'}),required=True)
    
    score=forms.IntegerField(
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Score Game'}),required=True)
    online=forms.BooleanField(
                               widget=forms.CheckboxInput({
                                   'class': 'form-control',
                                   'placeholder': 'Score Game'}),required=False)
    
    pegi=forms.IntegerField(
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'temporada de la Serie'}),required=True)
    class Meta:
        model = Game
        fields = [

            "name",
            "publisher",
            "year",
            "genre",
            "platform",
            "score",
            "online",
            "pegi"

    ]


class FormFilter():
    dataSearch=forms.CharField(max_length=20,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Search...'}))

VideogamesCodex/VideogamesCodex/app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Use this area to provide additional information.</p>

{% endblock %}

VideogamesCodex/VideogamesCodex/app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

{% endblock %}

VideogamesCodex/VideogamesCodex/app/templates/app/errors.html
{% extends "app/layout.html" %}

{% block  content %}
<h2>Error 404: Element not found</h2>
{% for error in errores %}
 <p>{{error}}</p>
{%endfor%}
{% endblock %}

VideogamesCodex/VideogamesCodex/app/templates/app/formGame.html
{% extends "app/layout.html" %}

{% block content %}
{% if divError %}
<div class="alert alert-danger alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">x</a>
            <strong>Error!</strong> {{error}}
          </div>
{%endif%}
<div class="container">
    <h2>{{title}}</h2>
<form method='POST' action='' >{% csrf_token %}
                <div class="form-group row">
                    <label for="id_name" class="col-md-2 control-label">Name</label>
                    <div class="col-md-10">
                        {{ form.name }}
                    </div>
                </div>
                    <div class="form-group row">
                    <label for="id_publisher" class="col-md-2 control-label">Publisher</label>
                    <div class="col-md-10">
                        {{ form.publisher }}
                    </div>
                </div>
                    <div class="form-group row">
                    <label for="id_year" class="col-md-2 control-label">Year</label>
                    <div class="col-md-10">
                        {{ form.year }}
                    </div>
                </div>
                    <div class="form-group row">
                    <label for="id_genre" class="col-md-2 control-label">Genre</label>
                    <div class="col-md-10">
                        {{ form.genre }}
                    </div>
                </div>
               <div class="form-group row">
                    <label for="id_platform" class="col-md-2 control-label">Platform</label>
                    <div class="col-md-10">
                        {{ form.platform }}
                    </div>
                </div>
                   <div class="form-group row">
                    <label for="id_score" class="col-md-2 control-label">Score</label>
                    <div class="col-md-10">
                        {{ form.score }}
                    </div>
                </div>
                       <div class="form-group row">
                    <label for="id_online" class="col-md-2 control-label">Online</label>
                    <div class="col-md-10">
                        {{ form.online }}
                    </div>
                </div>
                       <div class="form-group row">
                    <label for="id_pegi" class="col-md-2 control-label">PEGI</label>
                    <div class="col-md-10">
                        {{ form.pegi }}
                    </div>
                </div>

               <div class="form-group row">
                   <div class="offset-sm-10 col-sm-2">
                   <button type="submit" class="btn btn-primary">Save</button>
                       </div>
                   </div>


    

</form>
</div>

{% endblock %}

VideogamesCodex/VideogamesCodex/app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}


{% if divError %}
<div class="alert alert-danger alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">x</a>
            <strong>Error!</strong> {{error}}
          </div>
{%endif%}
<div class="jumbotron">
            
    <h1>{{title}}</h1>
    <p class="lead">Aprovecha nuestra juegos en 3D.</p>
    <p><a href="{% url 'create' %}" class="btn btn-warning btn-large">New Game</a></p>
     <form method='GET' action='' >{% csrf_token %}
                <div  class="row">
                <div class="col-lg-4">
                    <div class="input-group">
                        <input type="text" id="dataSearch" name="dataSearch" class="form-control" placeholder="Search..." maxlength="50" required="" >
                        <span class="input-group-btn">
                            <button class="btn btn-primary" type="submit">Search</button>
                        </span>
                    </div>
                </div>
                </div>
    </form>
</div>

<div class="container">
<div class="table-responsive">
	<table class="table table-hover">
		<thead>
			<tr>
				<th >Name</th>
                <th>Publisher</th>
                <th>Genre</th>
                <th>Actions</th>
			</tr>
		</thead>
		<tbody>
            {% for game in games %}
			<tr>
				<td>{{game.name}}</td>
                <td>{{game.publisher}}</td>
                <td>{{game.get_genre_display}}</td>
                <td><a role="button" href="{% url 'show' id=game.id %}" class="btn btn-success btn-large">Show</a></td>
			</tr>
            {% endfor %}
		</tbody>
	</table>
</div>
</div>

{% endblock %}

VideogamesCodex/VideogamesCodex/app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - VideoGames Codex</title>
     {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">VideoGames</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/ranking">Ranking</a></li>
                </ul>
               
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; 17-11-2017 - Video Games Django by Aziz labib</p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
    <script src="{% static 'app/scripts/s.js' %}"></script>
{% block scripts %}

    {% endblock %}

</body>
</html>

VideogamesCodex/VideogamesCodex/app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Use a local account to log in.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">User name</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Password</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Please enter a correct user name and password.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

VideogamesCodex/VideogamesCodex/app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Hello {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
    </ul>

</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Log in</a></li>
</ul>

{% endif %}

VideogamesCodex/VideogamesCodex/app/templates/app/ranking.html
{% extends "app/layout.html" %}

{% block content %}
<div class="container">
    <h1>Lista de {{title}}</h1>

	<table class="table table-hover">
		<thead>
			<tr>
				<th >Name</th>
                <th>Score</th>
                <th>Actions</th>
			</tr>
		</thead>
		<tbody>
            {% for pk,name,score in games %}
			<tr>
				<td>{{name}}</td>
                <td>{{score}}</td>
                <td><a role="button" href="/show/{{pk}}" class="btn btn-success btn-large">Show</a></td>
			</tr>
            {% endfor %}
		</tbody>
	</table>
</div>

{% endblock %}

VideogamesCodex/VideogamesCodex/app/templates/app/show.html
{% extends "app/layout.html" %}

{% block content %}
<div class="container">
    <div class="panel panel-warning">
        <h1 class="text-center">{{game.name}}</h1>
	<div class="panel-heading">
		<h1 class="panel-title">{{title}}</h1>
	</div>
	<div class="panel-body">
        <p><a href="{% url 'edit' id=game.id %}" class="btn btn-warning btn-large">Edit</a>
        <a onclick="return confirm('¿You want to delete this Game?');"href="{% url 'remove' id=game.id %}" class="btn btn-danger btn-large">Remove</a><p>
        <dl class="dl-horizontal">
            <dt>Name</dt>
            <dd>{{game.name}}</dd>
            <dt>Publisher</dt>
            <dd>{{game.publisher}}</dd>
            <dt>Year</dt>
            <dd>{{game.year}}</dd>
            <dt>Genre</dt>
            <dd>{{game.get_genre_display}}</dd>
            <dt>Platform</dt>
            <dd>{{game.get_platform_display}}</dd>
            <dt>Score</dt>
            <dd>{{game.score}}</dd>
            <dt>Online</dt>
            <dd>{{game.online}}</dd>
            <dt>PEGI</dt>
            <dd>{{game.pegi}}</dd>
        </dl>

	</div>
</div>
</div>

{% endblock %}