DjangoSerieTv/DjangoSerieTv/DjangoSerieTv/urls.py
"""
Definition of urls for DjangoSerieTv.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views

import app.forms
import app.views

# Uncomment the next lines to enable the admin:
# from django.conf.urls import include
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^ver/(?P<id>[0-9]+)$', app.views.ver, name='ver'),
    url(r'^editar/(?P<id>[0-9]+)$', app.views.editar, name='editar'),
    url(r'^borrar/(?P<id>[0-9]+)$', app.views.borrar, name='borrar'),
    url(r'^listar/(?P<data>[a-zA-Z]+)$', app.views.listar, name='listar'),
    url(r'^verData/(?P<tipo>[a-zA-Z]+)/(?P<data>[a-zA-Z0-9\s]+)$', app.views.verData, name='verData'),
    url(r'^crear$', app.views.crear, name='crear'),
    #url(r'^login/$',
    #    django.contrib.auth.views.login,
    #    {
    #        'template_name': 'app/login.html',
    #        'authentication_form': app.forms.BootstrapAuthenticationForm,
    #        'extra_context':
    #        {
    #            'title': 'Log in',
    #            'year': datetime.now().year,
    #        }
    #    },
    #    name='login'),
    #url(r'^logout$',
    #    django.contrib.auth.views.logout,
    #    {
    #        'next_page': '/',
    #    },
    #    name='logout'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
]

DjangoSerieTv/DjangoSerieTv/app/models.py
"""
Definition of models.
"""

from django.db import models

# Create your models here.
class Serie(models.Model):
    titulo = models.CharField(max_length=20)
    productora = models.CharField(max_length=10)
    fecha = models.IntegerField()
    temporada = models.IntegerField()
    GENEROS = ((0,"Accion"),(1,"Historica"),(2,"Terror"),(3,"Drama"),(4,"Ficcion"),(5,"Policiaca"))
    genero = models.IntegerField(choices=GENEROS)
    ESTADO = ((0,"Produccion"),(1,"En Emision"),(2,"Finalizada"))
    estado = models.IntegerField(choices=ESTADO)

    #devolver todas las series
    def getSeries():
        series = Serie.objects.all()
        return series
    #devolver una serie
    def getSerie(clave):
        serie = Serie.objects.get(pk=clave)
        return serie
    #devolver todas la lista del parametro de entrada
    def getListas(data):
        lista = []
        if data.lower() == "genero":
            series = Serie.objects.values_list(data,flat=True)
            for x in series:
                for k,v in Serie.GENEROS:
                    if k == x:
                        lista.append(v)
    
    
        else:
            lista = Serie.objects.values_list(data,flat=True).order_by(data)
        return lista

    def getSeriesByFilter(tipo,data):
        if tipo == "genero":
            for k,v in Serie.GENEROS:
                if v == data:
                    series = Serie.objects.values_list("id","titulo").filter(genero=k)
                    return series
        elif tipo=="fecha":
            series = Serie.objects.values_list("id","titulo").filter(fecha=data)
            return series
        elif tipo=="productora":
            series = Serie.objects.values_list("id","titulo").filter(productora=data)
            return series
        elif tipo=="todos":
            series = Serie.objects.filter(titulo__icontains=data)|Serie.objects.filter(productora__icontains=data)
            return series

class ModelFilter(models.Model):
    dataFilter = models.CharField(max_length=20

        

DjangoSerieTv/DjangoSerieTv/app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from app.models import Serie
from app.models import ModelFilter

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))


class QueryForm(forms.ModelForm):
    titulo=forms.CharField(max_length=20,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Titulo de la Serie'}))
    productora=forms.CharField(max_length=10,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Productora de la Serie'}))
    fecha=forms.IntegerField(
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Año de la Serie'}))
    temporada=forms.IntegerField(
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'temporada de la Serie'}))
    genero=forms.ChoiceField(choices=Serie.GENEROS,
                               widget=forms.Select({
                                   'class': 'form-control'}))
    estado=forms.ChoiceField(choices=Serie.ESTADO,
                               widget=forms.Select({
                                   'class': 'form-control'}))
    class Meta:
        model = Serie
        fields = [

            "titulo",
            "productora",
            "fecha",
            "temporada",
            "genero",
            "estado",

    ]

class FormFilter(forms.ModelForm):
    dataFilter=forms.CharField(max_length=20,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Buscar una serie...'}))
    class Meta:
        model=ModelFilter
        fields = [

            "dataFilter"

    ]
    

DjangoSerieTv/DjangoSerieTv/app/views.py
"""
Definition of views.
"""

from django.shortcuts import render
from django.http import HttpRequest
from django.http import HttpResponseRedirect
from django.template import RequestContext
from datetime import datetime
from app.models import Serie
from app.forms import QueryForm
from app.forms import FormFilter



def home(request):
    form = FormFilter(request.POST or None)
    series=[]
    errores=[]
    if form.is_valid():
        instance=form.instance.dataFilter
        series = Serie.getSeriesByFilter("todos",instance)
        
    else:
        series = Serie.getSeries()
    return render(request,
        'app/index.html',
        {
            'title':'Serie tv',
            'series':series,
            'form':form,
            'errores':errores
        })

def ver(request,id):
    """Renders the about page."""
    assert isinstance(request, HttpRequest)
    serie = Serie.getSerie(id)
    return render(request,
        'app/ver.html',
        {
            'title':'Informacion Serie',
            'serie':serie
        })

def crear(request):
    form = QueryForm(request.POST or None)

    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return HttpResponseRedirect('/ver/%s' % instance.id)
        
    context = {

        "title":"Crear Nueva Serie",
        "form": form,

    }

    return render(request, "app/serieForm.html", context)



def editar(request,id):
    #comprobar si el parametro id es correcto
    if id=="":
        return render(request, "app/serieForm.html", context)
    
    serie = Serie.getSerie(id)
    form = QueryForm(request.POST or None,instance=serie)
    if form.is_valid():
        instance2 = form.save(commit=False)
        instance2.save()
        return HttpResponseRedirect('/ver/%s' % instance2.id)

    context = {
        "title":"Editar Serie",
        "form": form
        }
    return render(request, "app/serieForm.html", context)

def borrar(request,id):
    Serie.objects.filter(pk=id).delete()
    return HttpResponseRedirect('/')

def listar(request,data):
    lista=Serie.getListas(data)
    lista2=set(lista)
    datas=data.capitalize()
    context = {
        "title":datas,
        "lista":lista2
        }
    return render(request, "app/listTemplate.html", context)

def verData(request,tipo,data):
    series=Serie.getSeriesByFilter(tipo.lower(),data)
    
    context = {
        "title":data,
        "series":series
        }
    return render(request, "app/verData.html", context)
    

DjangoSerieTv/DjangoSerieTv/app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}

        {% for error in errores %}
          <div class="alert alert-danger alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">x</a>
            <strong>Error!</strong> {{error}}
          </div>
        {% endfor %}

<div class="jumbotron">
            
    <h1>{{title}}</h1>
    <p class="lead">Aprovecha nuestra series en 4K.</p>
    <p><a href="{% url 'crear' %}" class="btn btn-warning btn-large">Crear nueva Serie</a></p>
    <form method='POST' action='' >{% csrf_token %}
                <div class="form-group row">
                    <div class="col-md-10">
                        {{ form.dataFilter }}
                    </div>
                    <div class="col-md-2">
                    <button type="submit" class="btn btn-primary">Buscar</button>
                    </div>
                </div>
    </form>
</div>

<div class="container">
<div class="table-responsive">
	<table class="table table-hover">
		<thead>
			<tr>
				<th >Titulo</th>
                <th>Productora</th>
                <th>Estado</th>
                <th>Temporada</th>
                <th>A&ntilde;o</th>
                <th>Acciones</th>
			</tr>
		</thead>
		<tbody>
            {% for serie in series %}
			<tr>
				<td>{{serie.titulo}}</td>
                <td>{{serie.productora}}</td>
                <td>{{serie.get_estado_display}}</td>
                <td>{{serie.temporada}}</td>
                <td>{{serie.fecha}}</td>
                <td><a role="button" href="{% url 'ver' id=serie.id %}" class="btn btn-warning btn-large">Ver</a></td>
			</tr>
            {% endfor %}
		</tbody>
	</table>
</div>
</div>

{% endblock %}

DjangoSerieTv/DjangoSerieTv/app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - Serie Tv </title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">Serie Tv</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/listar/genero">Generos</a></li>
                    <li><a href="/listar/fecha">A&ntilde;os</a></li>
                    <li><a href="/listar/productora">Productoras</a></li>
                </ul>
                {#{% include 'app/loginpartial.html' %}#}
            </div>
        </div>
    </div>

    <div class="container body-content">

{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; 2017 - Serie Tv by Aziz labib </p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

DjangoSerieTv/DjangoSerieTv/app/templates/app/listTemplate.html
{% extends "app/layout.html" %}

{% block content %}
<div class="container">
    <h1>Lista de {{title}}</h1>
<ul class="list-inline">
    {% for v in lista %}
  <li><a class="btn btn-warning" href="/verData/{{title}}/{{v}}" role="button">
    {{v}}</a>
      </li>
    {% endfor %}
</ul>

</div>

{% endblock %}

DjangoSerieTv/DjangoSerieTv/app/templates/app/serieForm.html
{% extends "app/layout.html" %}

{% block content %}
<div class="container">
    <h2>{{title}}</h2>
<form method='POST' action='' >{% csrf_token %}
                <div class="form-group row">
                    <label for="id_titulo" class="col-md-2 control-label">Titulo</label>
                    <div class="col-md-10">
                        {{ form.titulo }}
                    </div>
                </div>
                    <div class="form-group row">
                    <label for="id_productora" class="col-md-2 control-label">Productora</label>
                    <div class="col-md-10">
                        {{ form.productora }}
                    </div>
                </div>
                    <div class="form-group row">
                    <label for="id_fecha" class="col-md-2 control-label">a&ntilde;o</label>
                    <div class="col-md-10">
                        {{ form.fecha }}
                    </div>
                </div><div class="form-group row">
                    <label for="id_temporada" class="col-md-2 control-label">Temporada</label>
                    <div class="col-md-10">
                        {{ form.temporada }}
                    </div>
                </div>
                    <div class="form-group row">
                    <label for="id_genero" class="col-md-2 control-label">Genero</label>
                    <div class="col-md-10">
                        {{ form.genero }}
                    </div>
                </div>
               <div class="form-group row">
                    <label for="id_estado" class="col-md-2 control-label">Estado</label>
                    <div class="col-md-10">
                        {{ form.estado }}
                    </div>
                </div>
               <div class="form-group row">
                   <div class="offset-sm-10 col-sm-2">
                   <button type="submit" class="btn btn-primary">Guardar Datos</button>
                       </div>
                   </div>


    

</form>
</div>

{% endblock %}

DjangoSerieTv/DjangoSerieTv/app/templates/app/ver.html
{% extends "app/layout.html" %}

{% block content %}
<div class="container">
    <div class="panel panel-warning">
        <h1 class="text-center">{{serie.titulo}}</h1>
	<div class="panel-heading">
		<h1 class="panel-title">{{title}}</h1>
	</div>
	<div class="panel-body">
        <p><a href="{% url 'editar' id=serie.id %}" class="btn btn-warning btn-large">Editar</a>
        <a onclick="return confirm('¿Deseas eliminar esta Serie?');"href="{% url 'borrar' id=serie.id %}" class="btn btn-danger btn-large">Borrar</a><p>
        <dl class="dl-horizontal">
            <dt>Titulo</dt>
            <dd>{{serie.titulo}}</dd>
            <dt>Productora</dt>
            <dd>{{serie.productora}}</dd>
            <dt>A&ntilde;o</dt>
            <dd>{{serie.fecha}}</dd>
            <dt>Temporada</dt>
            <dd>{{serie.temporada}}</dd>
            <dt>Genero</dt>
            <dd>{{serie.get_genero_display}}</dd>
            <dt>Estado</dt>
            <dd>{{serie.get_estado_display}}</dd>
        </dl>

	</div>
</div>
</div>

{% endblock %}

DjangoSerieTv/DjangoSerieTv/app/templates/app/verData.html
{% extends "app/layout.html" %}

{% block content %}
<div class="container">
    <h1>Series de {{title}}</h1>
<table class="table table-hover">
		<thead>
			<tr>
				<th>Titulo</th>
                <th>Acciones</th>
			</tr>
		</thead>
		<tbody>
            {% for k,v in series %}
			<tr>
				<td>{{v}}</td>
                <td><a role="button" href="{% url 'ver' id=k %}" class="btn btn-warning btn-large">Ver</a></td>
			</tr>
            {% endfor %}
		</tbody>
	</table>

</div>

{% endblock %}